
// export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE'

// export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE'

// export const UPDATE_REQUEST = 'USERS_UPDATE_REQUEST'
export const UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const UPDATE_FAILURE = 'USER_UPDATE_FAILURE'
